sudo: false

language: python

python:
  - 2.7
  - 3.5

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=offenewahlen_api.settings_testing

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres


script:
  - cd src/
  - pytest --doctest-modules --cov=austria --cov-report term-missing austria/tests/

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - admin@stefankasberger.at
    on_success: change
    on_failure: change
