sudo: false

language: python

python:
  - 2.7
  - 3.5

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=offenewahlen_api.settings_testing

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - coverage run --source=. src/manage.py test austria --noinput

script:
  - python src/manage.py test

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - admin@stefankasberger.at
    on_success: change
    on_failure: change
