# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('short_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('election_type', models.CharField(max_length=100)),
                ('election_id', models.CharField(max_length=20, null=True)),
                ('wikidata_id', models.CharField(max_length=20, null=True, unique=True)),
                ('administrative_level', models.CharField(max_length=100)),
                ('election_day', models.DateTimeField(verbose_name='timestamp of election day')),
                ('state', models.CharField(default='init', max_length=200)),
            ],
            options={
                'verbose_name': 'election',
                'verbose_name_plural': 'elections',
                'ordering': ['short_name'],
                'get_latest_by': 'election_day',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(default=None, max_length=50)),
                ('full_name', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='ListResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=-1, null=True)),
            ],
            options={
                'verbose_name': 'list result',
                'verbose_name_plural': 'list results',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kennzahl', models.CharField(default=None, max_length=5)),
            ],
            options={
                'verbose_name': 'municipality',
                'verbose_name_plural': 'municipalities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(default=None, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('family', models.CharField(default=None, max_length=200, null=True)),
                ('wikidata_id', models.CharField(default=None, max_length=20, null=True, unique=True)),
                ('website', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'party',
                'verbose_name_plural': 'parties',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'polling station',
                'verbose_name_plural': 'polling stations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollingStationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eligible_voters', models.IntegerField(default=-1, null=True)),
                ('votes', models.IntegerField(default=-1)),
                ('valid', models.IntegerField(default=-1)),
                ('invalid', models.IntegerField(default=-1)),
                ('ts_result', models.DateTimeField(verbose_name='timestamp of bmi result')),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'polling station result',
                'verbose_name_plural': 'polling station results',
                'ordering': ['id'],
                'get_latest_by': 'ts_result',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_file', models.DateTimeField(null=True, verbose_name='creation date of original file')),
                ('ts_import', models.DateTimeField(default=None, verbose_name='import date of file into database')),
                ('hash', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('header', models.TextField(default=None, null=True)),
                ('dataformat', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'raw data',
                'verbose_name_plural': 'raw data',
                'ordering': ['id'],
                'get_latest_by': 'ts_file',
            },
        ),
        migrations.CreateModel(
            name='RegionalElectoralDistrict',
            fields=[
                ('short_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'regional electoral district',
                'verbose_name_plural': 'regional electoral districts',
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('short_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
                'ordering': ['short_code'],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name', 'short_code'], name='viz_state_name_110767_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalelectoraldistrict',
            index=models.Index(fields=['name', 'short_code'], name='viz_regiona_name_4209e9_idx'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.Election'),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.Election'),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='polling_station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.PollingStation'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.Municipality'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['full_name', 'short_name', 'short_name_text'], name='viz_party_full_na_7949a8_idx'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.District'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='regional_electoral_district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.RegionalElectoralDistrict'),
        ),
        migrations.AddField(
            model_name='listresult',
            name='election_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viz.List'),
        ),
        migrations.AddField(
            model_name='listresult',
            name='polling_station_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viz.PollingStationResult'),
        ),
        migrations.AddField(
            model_name='list',
            name='party',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='viz.Party'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['full_name', 'short_name', 'short_name_text'], name='viz_electio_full_na_cc25f1_idx'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.State'),
        ),
        migrations.AddIndex(
            model_name='pollingstation',
            index=models.Index(fields=['name'], name='viz_polling_name_ef3438_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['name', 'code', 'kennzahl'], name='viz_municip_name_e95d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['short_name', 'full_name', 'short_name_text'], name='viz_list_short_n_ddc933_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name', 'short_code'], name='viz_distric_name_5ff095_idx'),
        ),
    ]
