# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_auto_20170926_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtresult',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtresult',
            name='election',
        ),
        migrations.RemoveField(
            model_name='listdistrictresult',
            name='district_result',
        ),
        migrations.RemoveField(
            model_name='listdistrictresult',
            name='election_list',
        ),
        migrations.RemoveField(
            model_name='listredresult',
            name='election_list',
        ),
        migrations.RemoveField(
            model_name='listredresult',
            name='red_result',
        ),
        migrations.RemoveField(
            model_name='liststateresult',
            name='election_list',
        ),
        migrations.RemoveField(
            model_name='liststateresult',
            name='state_result',
        ),
        migrations.RemoveField(
            model_name='redresult',
            name='election',
        ),
        migrations.RemoveField(
            model_name='redresult',
            name='regional_electoral_district',
        ),
        migrations.RemoveField(
            model_name='stateresult',
            name='election',
        ),
        migrations.RemoveField(
            model_name='stateresult',
            name='state',
        ),
        migrations.DeleteModel(
            name='DistrictResult',
        ),
        migrations.DeleteModel(
            name='ListDistrictResult',
        ),
        migrations.DeleteModel(
            name='ListREDResult',
        ),
        migrations.DeleteModel(
            name='ListStateResult',
        ),
        migrations.DeleteModel(
            name='REDResult',
        ),
        migrations.DeleteModel(
            name='StateResult',
        ),
    ]
