# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0004_auto_20171010_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresultpollingstationimport',
            name='import_file',
        ),
        migrations.RemoveField(
            model_name='checkresultpollingstationimport',
            name='polling_station',
        ),
        migrations.DeleteModel(
            name='CheckResultFileImport',
        ),
        migrations.DeleteModel(
            name='CheckResultPollingStationImport',
        ),
    ]
