# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('short_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'districts',
                'verbose_name': 'district',
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('election_type', models.CharField(max_length=100)),
                ('election_id', models.CharField(max_length=20, null=True)),
                ('wikidata_id', models.CharField(max_length=20, null=True, unique=True)),
                ('administrative_level', models.CharField(max_length=100)),
                ('election_day', models.DateTimeField(verbose_name='timestamp of election day')),
                ('status', models.CharField(default='init', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'elections',
                'ordering': ['short_name'],
                'verbose_name': 'election',
                'get_latest_by': 'election_day',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(default=None, max_length=50)),
                ('full_name', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'lists',
                'verbose_name': 'list',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='ListResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=-1, null=True)),
            ],
            options={
                'verbose_name_plural': 'list results',
                'verbose_name': 'list result',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kennzahl', models.CharField(default=None, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'verbose_name': 'municipality',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name_text', models.CharField(default=None, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('family', models.CharField(default=None, max_length=200, null=True)),
                ('wikidata_id', models.CharField(default=None, max_length=20, null=True, unique=True)),
                ('website', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'parties',
                'verbose_name': 'party',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'polling stations',
                'verbose_name': 'polling station',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollingStationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eligible_voters', models.IntegerField(default=-1, null=True)),
                ('votes', models.IntegerField(default=-1)),
                ('valid', models.IntegerField(default=-1)),
                ('invalid', models.IntegerField(default=-1)),
                ('ts_result', models.DateTimeField(verbose_name='timestamp of bmi result')),
            ],
            options={
                'verbose_name_plural': 'polling station results',
                'ordering': ['id'],
                'verbose_name': 'polling station result',
                'get_latest_by': 'ts_result',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_file', models.DateTimeField(null=True, verbose_name='creation date of original file')),
                ('ts_import', models.DateTimeField(default=None, verbose_name='import date of file into database')),
                ('hash', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('header', models.TextField(default=None, null=True)),
                ('dataformat', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
            ],
            options={
                'verbose_name_plural': 'raw data',
                'ordering': ['id'],
                'verbose_name': 'raw data',
                'get_latest_by': 'ts_file',
            },
        ),
        migrations.CreateModel(
            name='RegionalElectoralDistrict',
            fields=[
                ('short_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'regional electoral districts',
                'verbose_name': 'regional electoral district',
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('short_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'states',
                'verbose_name': 'state',
                'ordering': ['short_code'],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name', 'short_code'], name='austria_sta_name_6993c1_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalelectoraldistrict',
            index=models.Index(fields=['name', 'short_code'], name='austria_reg_name_b53223_idx'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.Election'),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.Election'),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='polling_station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.PollingStation'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.Municipality'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['full_name', 'short_name', 'short_name_text'], name='austria_par_full_na_2a1baa_idx'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.District'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='regional_electoral_district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.RegionalElectoralDistrict'),
        ),
        migrations.AddField(
            model_name='listresult',
            name='election_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='austria.List'),
        ),
        migrations.AddField(
            model_name='listresult',
            name='polling_station_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='austria.PollingStationResult'),
        ),
        migrations.AddField(
            model_name='list',
            name='party',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='austria.Party'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['full_name', 'short_name', 'short_name_text'], name='austria_ele_full_na_bbb3c0_idx'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='austria.State'),
        ),
        migrations.AddIndex(
            model_name='pollingstation',
            index=models.Index(fields=['name'], name='austria_pol_name_56e525_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['name', 'code', 'kennzahl'], name='austria_mun_name_329503_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['short_name', 'full_name', 'short_name_text'], name='austria_lis_short_n_4b5871_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name', 'short_code'], name='austria_dis_name_e39bb2_idx'),
        ),
    ]
