# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResultFileImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_not_present', models.BooleanField()),
                ('all_checks_true', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'basedata check',
                'verbose_name_plural': 'basedata checks',
            },
        ),
        migrations.CreateModel(
            name='CheckResultPollingStationImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_is_sumparties', models.BooleanField()),
                ('valid_plus_invalid_equal_votes', models.BooleanField()),
                ('eligiblevoters_greaterequalthan_votes', models.BooleanField()),
                ('allproperties_available', models.BooleanField()),
                ('not_more_properties_than_necessary', models.BooleanField()),
                ('timestamp_ascending', models.BooleanField()),
                ('timestamp_between_start_and_now', models.BooleanField()),
                ('all_checks_true', models.BooleanField()),
                ('import_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.CheckResultFileImport')),
                ('polling_station', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='viz.PollingStation')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'result check',
                'verbose_name_plural': 'result checks',
            },
        ),
        migrations.RenameField(
            model_name='election',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='pollingstationresult',
            name='is_final',
        ),
    ]
